import csv
import pickle

# Convert .csv file to .pkl file in same format as expected by SAM-SLR model
# Generated by OpenAI's ChatGPT
def convert_csv_to_pkl(csv_path, out_path):
    sample_names = []
    labels = []

    # Read the CSV file
    with open(csv_path, 'r', newline='') as csv_file:
        csv_reader = csv.reader(csv_file)
        for row in csv_reader:
            sample_names.append(row[0])
            label = int(row[1])
            labels.append(label)

    # Create a list with two rows
    data_list = [sample_names, labels]

    with open(out_path, 'wb') as pkl_file:
        pickle.dump(data_list, pkl_file)

# Load .csv file and write .pkl file
# Change according to analysed dataset
csv_path = '/home/Student/s4582342/train_val_labels.csv'
out_path = '/home/Student/s4582342/CVPR21Chal-SLR/SL-GCN/data/sign/27_2/train_val_labels.pkl'
convert_csv_to_pkl(csv_path, out_path)
